### PR TITLE
Feature/admin

### LINKED ISSUE #367: Python client async updgrade
Add  python async capable versions of the following fluvio python client capabilities.  

- 'PartitionConsumer`
    - stream
    - stream_with_config
 
- `MultiplePartitionConsumer`
    - stream
    - stream_with_config
    
- `TopicProducer` 
    - send
    - flush
    - send_all

The producer and consumer capabilities should also be able to be instantiated with config options in order to run with smartmodules.  See Fluvio rust examples where config structs can specify smartmodules and their parameters to execute.

- [`fn fluvio_producer_with_config(...)`](https://github.com/infinyon/fluvio/blob/0f9bc1eac1aeecefff6aff85cf69a8a4d244b89f/crates/fluvio/src/fluvio.rs#L172)
- [`PartitionConsumer::stream_with_config`](https://github.com/infinyon/fluvio/blob/0f9bc1eac1aeecefff6aff85cf69a8a4d244b89f/crates/fluvio/src/consumer.rs#L168)
-  [`MultiplePartitionConsumer::stream_with_config`](https://github.com/infinyon/fluvio/blob/0f9bc1eac1aeecefff6aff85cf69a8a4d244b89f/crates/fluvio/src/consumer.rs#L720)

The async additions should not interfere the simpler sync versions . If it makes the implementation easier, a set of async classes could be created e.g. AsyncPartitionConsumer. Though if possible a single class is preferred with methods to create sync and async produce and consume objs.

Ref:
- fluvio rust crate docs https://docs.rs/fluvio/latest/fluvio/
- fluvio python docs  https://infinyon.github.io/fluvio-client-python/fluvio.html

### PR DESCRIPTION
**Pull request by Shylock-Hg**
Close #367 
/claim https://github.com/infinyon/fluvio/issues/3859

### CODE REVIEW

**Comment by digikata** [comment]
Hi @Shylock-Hg, its great to see progress getting closer, though re: the bounty claim,  I think we need to have the existing tests pass as well as test coverage for the new capability in admin and async.    I know ghub was having some issues fri, so I'll rerun some of these tests too.

**Comment by digikata** [comment]
@Shylock-Hg can you rebase?  There is a fix for the macos build CI.  Some upstream config was breaking the build.  This should let us test with  the full CI.

**Comment by digikata** [comment]
Hi @Shylock-Hg, we released fluvio 0.11.5 with your upstreamed changes in it for the python client.  I rebased both your PRs and did some selected merging to update the references.     There are just some cargo clippy issues to take care of.     I don't know the easiest way for you to claim it, but maybe pull the branch https://github.com/infinyon/fluvio-client-python/tree/pre-0.17.0, do the cleanup and claim on that result?

**Comment by digikata** [comment]
@Shylock-Hg Thanks for the async updates,  I checked the async PR, made some very minor `cargo fmt` fixes and merged it, so t he only thing we need to worry about is rebaseng this pr, maybe some clippy fixes, and input from our two heavy python users.

**Comment by digikata** [comment]
@Shylock-Hg If you could rebase onto main, I think we are ready to merge and sign off on the bounty (cc: @drc-infinyon )

**Comment by digikata** [comment]
Thanks @Shylock-Hg !

**Comment by drc-infinyon** [comment]
@Shylock-Hg - This ticket is resolved.

You need to claim the bounty based on this workflow: https://docs.algora.io/bounties/workflow - 

To claim a bounty on Github, navigate to your pull request that solves the bountied issue and add `/claim <ISSUE_NUMBER>` somewhere in the body of the PR.

**Pull request merged**
