### PR TITLE
[Merged by Bors] - feat: added timestamp method to Record 

### LINKED ISSUE #193: Add timestamps to Record API
This should be pretty easy.

### PR DESCRIPTION
**Pull request by viniarck**
Closes #193

After adding the feature, I've also reinstalled the rust extension and ran this example:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from fluvio import Fluvio, Offset

fluvio = Fluvio.connect()
consumer = fluvio.partition_consumer("lobby", 0)
stream = consumer.stream(Offset.beginning())

for rec in stream:
    print(f"value: {rec.value_string()}, timestamp: {rec.timestamp()}")
```

```
❯ python examples/consumer.py 
value: hello, timestamp: 1668107698731
value: 1, timestamp: 1668107699960
value: 2, timestamp: 1668107699960
value: 3, timestamp: 1668107699960
value: 4, timestamp: 1668107699960
value: 5, timestamp: 1668107699961
value: 6, timestamp: 1668107699961
value: 7, timestamp: 1668107699961
value: 8, timestamp: 1668107699961
value: 9, timestamp: 1668107699961
value: 10, timestamp: 1668107699961
```

### CODE REVIEW

**Comment by sehz** [comment]
Thanks for contributing

**Review by morenol — APPROVED** [review]
LGTM

**Comment by sehz** [comment]
CI is failing.  Any idea why? @morenol @tjtelan

**Comment by tjtelan** [comment]
It looks like the smoke test setup steps all fail on the CLI commands used, and so all the tests fail too.
https://github.com/infinyon/fluvio-client-python/actions/runs/4608241927/jobs/8145119636?pr=244#step:11:342

**Comment by viniarck** [comment]
@morenol @sehz @tjtelan, I went ahead and fixed the failing tests too. I've also added an integration test to cover Record's `timestamp()` method. Could you guys do another review? Let me know if you prefer the ci fixes in another PR.

Integration tests are passing locally:

```
❯ make integration-tests
python3 -m venv venv
...


----------------------------------------------------------------------
Ran 24 tests in 215.681s

OK
```

**Comment by sehz** [comment]
CI still failing.

**Comment by viniarck** [comment]
> CI still failing.

@sehz, from what I traced, the integration test issue is two-fold:

1) Sometimes certain fluvio resources fail to be provisioned. For instance, these errors from the last execution, `EEEE.....EE...only 0 out of 1 provisioned`, this came from [`fluvio-sc` public api when provisioning a topic](https://github.com/infinyon/fluvio/blob/master/crates/fluvio-sc/src/services/public_api/topic/create.rs#L237)
2) There's also non-deterministic potential bugs. For instance, when I ran the entire test suite locally again, 4 out 5 times all tests passed, but in one of the executions this following segfault happened, this looks like an actual bug, `fluvio smartmodule create cea27245-0ffb-47c1-b849-11ce1261bbd3 --wasm-file /home/viniarck/repos/fluvio-client-python/integration-tests/smartmodules-for-ci/smartmodule_filter_on_a.wasm' died with <Signals.SIGSEGV: 11>.`

Regarding point number 1, probably by increasing compute & ram resources of the runner/cluster it might improve. It'd be nice if the integration tests could retry some of the provisioning operations (at least until they get stable).

**Comment by sehz** [comment]
Can you retry using this ?https://github.com/marketplace/actions/retry-step.

For #2, segfault should not occur.  There is something else going on.  

I will review this one more time.  We can work on improving stability in subsequent PR

**Comment by viniarck** [comment]
> Can you retry using this ?https://github.com/marketplace/actions/retry-step.

Sure. Done on 7cb51d40474f08630d2413d75a7029529808545e. Looks like it needs approval from maintainers for the CI to run. 

Is this topic creation error `only 0 out of 1 provisioned` considered recoverable or not recoverable? If the topic eventually provisions without running the same command, then on test temporarily adding a `fluvio topic list` command to wait for status `resolution::provisioned` could be helpful to stabilize testing harness resource creation in the meantime.

> For #2, segfault should not occur. There is something else going on.

Right. Yes, maybe it might be something to explore in a stress test with a debug build.

**Comment by sehz** [comment]
> > Can you retry using this ?https://github.com/marketplace/actions/retry-step.
> 
> Sure. Done on [7cb51d4](https://github.com/infinyon/fluvio-client-python/commit/7cb51d40474f08630d2413d75a7029529808545e). Looks like it needs approval from maintainers for the CI to run.
> 
> Is this topic creation error `only 0 out of 1 provisioned` considered recoverable or not recoverable? If the topic eventually provisions without running the same command, then on test temporarily adding a `fluvio topic list` command to wait for status `resolution::provisioned` could be helpful to stabilize testing harness resource creation in the meantime.
> 
> > For #2, segfault should not occur. There is something else going on.
> 
> Right. Yes, maybe it might be something to explore in a stress test with a debug build.

Topic provisioning should not fail.  There are still rare failure.   Need to check if provisioning steps.  Only diff I see is that it's not using same k3d provisioning step as fluvio.

**Comment by morenol** [comment]
@viniarck I pushed some commits to solve conflicts with `master`. Thanks for your contribution!

**Comment by morenol** [comment]
bosr r+

**Comment by viniarck** [comment]
> @viniarck I pushed some commits to solve conflicts with `master`. Thanks for your contribution!

cool.

**Pull request closed without merging**
