### PR TITLE
New PyO3 bindings

### PR DESCRIPTION
**Pull request by urbit-pilled**
Since this repo already uses setuptools-rust, rebuilding with PyO3 is a simple change.
/claim [#3842](https://github.com/infinyon/fluvio/issues/3842)

### CODE REVIEW

**Comment by digikata** [comment]
Hi, thanks for the submission urbit-pilled!

The issue was intended to allow building and running the extension under python 3.12, which was unfortunately disabled in our CI at the time you submitted this PR. 

3.12 is enabled now in the CI so I wonder if you could rebase and see it it fares.

Thanks!

**Comment by urbit-pilled** [comment]
I just updated PyO3 to 0.20 as that was when python 3.12 support was added

https://github.com/PyO3/pyo3/blob/6040d93032027f86d66356f02d21e221c8998a58/CHANGELOG.md?plain=1#L52

**Comment by digikata** [comment]
Looks like the CI has some issues with building for python 3.12

- https://github.com/infinyon/fluvio-client-python/actions/runs/7719635825/job/21043275392
- https://github.com/infinyon/fluvio-client-python/actions/runs/7719635825/job/21043275582

Depending on what you're running you can locally run these tests with the repo Makefile `make integretation-tests` and/or `make macos-ci-tests`

**Comment by urbit-pilled** [comment]
```
ImportError: /home/runner/work/fluvio-client-python/fluvio-client-python/fluvio/_fluvio_python.cpython-312-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_Ready
```
Looks like the previous CI errors were due to Flapigen. I removed flapigen and recreated the bindings using PyO3.

**Comment by digikata** [comment]
That's some nice work @urbit-pilled.  Thanks!

**Comment by ajhunyady** [comment]
@urbit-pilled good job! Can you please ping me in Discord (https://discordapp.com/invite/bBG2dTz), I have a question on a new project for you.

**Pull request merged**
